language: node_js
node_js: 
    - 13
services:
    - docker
    
#pre-testing installs
install:
    - echo "Nothing needs to be installed"

#Script to be run such as test
before_script:
    - echo "No tests"
script:
    - docker build -t udagram-api-feed ./udagram-api-feed
    - docker tag udagram-api-feed rostykamga/udagram-api-feed:latest
    - docker build -t udagram-api-user ./udagram-api-user
    - docker tag udagram-api-user rostykamga/udagram-api-user:latest
    - docker build -t udagram-reverseproxy ./udagram-reverseproxy
    - docker tag udagram-reverseproxy rostykamga/udagram-reverseproxy:latest
    - docker build -t udagram-frontend ./udagram-frontend
    - docker tag udagram-frontend rostykamga/udagram-frontend:latest

# Tasks to perform after the process is successful. 
after_success:
    - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
    - docker push rostykamga/udagram-api-feed
    - docker push rostykamga/udagram-api-user
    - docker push rostykamga/udagram-reverseproxy
    - docker push rostykamga/udagram-frontend